services:
  earthquake_usgs:
    image: earthquake_usgs_cron:1.3.0
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/log/nearquake:/usr/src/app/logs
    healthcheck:
      test: [ "CMD", "python", "main.py" ]
      interval: 600s
      retries: 5
    restart: always
    env_file: .env
    networks:
      - nearquake-network

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${NEARQUAKE_USERNAME}
      POSTGRES_PASSWORD: ${NEARQUAKE_PASSWORD}
      POSTGRES_DB: ${NEARQUAKE_DATABASE}
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${NEARQUAKE_USERNAME}"]
      interval: 5s
      retries: 5
    restart: always
    networks:
      - nearquake-network

  datadog-agent:
    container_name: datadog-agent
    image: datadog/agent:latest
    environment:
      DD_API_KEY: ${DD_API_KEY}
      DD_LOGS_ENABLED: "true"
      DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL: "true"
      DD_CONTAINER_EXCLUDE_LOGS: "name:datadog-agent"
      DD_SITE: "us5.datadoghq.com"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /opt/datadog-agent/run:/opt/datadog-agent/run:rw
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    restart: unless-stopped
    networks:
      - nearquake-network

networks:
  nearquake-network:
  
volumes:
  postgres-db-volume: